##  1. Import Numpy

In [1]:
import numpy as np

## 2. Manually create a matrix 
Create a 3-by-5 matrix and print it out to the screen

In [2]:
a = np.array([(1,2,3,4,5), (6,7,8,9,10), (11,12,13,14,15)])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


## 3. Manually create a vector

Create a vector which has 10 elements and print it out to the screen

In [3]:
b = np.array([1,2,3,4,5,6,7,8,9,10])
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 4. Automatically create matrix

Automatically create a 3-by-5 matrix which has interger values in the range of [0, 100] 
Automatically create a 5-by-7 matrix which has interger values in the range of [0, 100]
Print out the above 2 matricces to the screen
Implementy matrix multiplication of the above 2 matrices and print the result to the screen (let us call this result matrixx is C)

In [4]:
n = np.random.randint(1,100,(3,5))
n

array([[19, 15, 39, 54,  9],
       [53, 61, 35, 23, 14],
       [87, 39, 52, 60, 45]])

In [5]:
m = np.random.randint(0,100,(5,7))
m

array([[76, 10, 88, 77, 39, 25, 33],
       [96, 95, 53, 80, 32, 43, 96],
       [56, 51, 10, 96, 44,  2,  6],
       [78,  7, 12,  7, 40, 20, 17],
       [25, 26, 61,  8, 58, 36, 29]])

In [6]:
c = n.dot(m)
c

array([[ 9505,  4216,  4054,  6857,  5619,  2602,  3480],
       [13988,  8635,  9377, 12594,  7291,  4982,  8612],
       [19073,  8817, 13708, 15591, 11939,  6776,  9252]])

## 5. Scalar multiplication

Input a number fromm keyboard and multiply this number with the above matrix C and print the result to the screen

In [7]:
x = int(input("Enter a Number = "))

Enter a Number = 10


In [8]:
x * c

array([[ 95050,  42160,  40540,  68570,  56190,  26020,  34800],
       [139880,  86350,  93770, 125940,  72910,  49820,  86120],
       [190730,  88170, 137080, 155910, 119390,  67760,  92520]])

## 6. Automatically create vector

Automattically create a vector at size of 7-by-1 which has values in the range of [-10, 30]. And multiply the C matrix with this vector. Print the result to the screen.

In [9]:
y = np.random.randint(-10,30,(7,1))
y

array([[-7],
       [ 0],
       [-1],
       [24],
       [20],
       [18],
       [24]])

In [10]:
cx_multiplication = c.dot(y)
print(cx_multiplication)

[[336715]
 [637147]
 [809761]]


##  7. Matrix slicing

1.Automatically create a matrix at size of 7-by-15

In [11]:
z = np.random.rand(7,15)
z

array([[0.08224651, 0.08592456, 0.33904997, 0.43718256, 0.23068324,
        0.9342249 , 0.23229351, 0.03756255, 0.9089843 , 0.26437046,
        0.62406673, 0.15484095, 0.0575529 , 0.02690438, 0.45392912],
       [0.53866733, 0.69971669, 0.3891356 , 0.30589863, 0.1818081 ,
        0.3558773 , 0.30152906, 0.8753454 , 0.54706505, 0.06435866,
        0.65335438, 0.97707152, 0.91635288, 0.20622579, 0.42793391],
       [0.52209879, 0.14715851, 0.40041449, 0.01960131, 0.43191804,
        0.85649108, 0.6176526 , 0.61219111, 0.45696665, 0.871961  ,
        0.26986717, 0.45659266, 0.50388664, 0.41201596, 0.38307933],
       [0.70989607, 0.46886248, 0.71671602, 0.42004158, 0.75529394,
        0.30189895, 0.29188171, 0.40969578, 0.19321512, 0.7439894 ,
        0.54006034, 0.19494348, 0.43496336, 0.54376609, 0.18595104],
       [0.28151634, 0.56909596, 0.47692375, 0.09490413, 0.16285912,
        0.44277464, 0.07711749, 0.07642623, 0.46164848, 0.50310792,
        0.88814036, 0.48209033, 0.29568235, 

2. Print out the first column of this matrix


In [12]:
z[0:7,0]

array([0.08224651, 0.53866733, 0.52209879, 0.70989607, 0.28151634,
       0.12027041, 0.87103075])

In [13]:
z[:,0]

array([0.08224651, 0.53866733, 0.52209879, 0.70989607, 0.28151634,
       0.12027041, 0.87103075])

3. Print out the third row of this matrix

In [14]:
z[2, :]

array([0.52209879, 0.14715851, 0.40041449, 0.01960131, 0.43191804,
       0.85649108, 0.6176526 , 0.61219111, 0.45696665, 0.871961  ,
       0.26986717, 0.45659266, 0.50388664, 0.41201596, 0.38307933])

4.Print out the element at the second column and fourth row


In [15]:
z[3, 1]

0.46886247633742195

## 8. Matrix transposition

In [16]:
i = np.transpose(z)
i

array([[0.08224651, 0.53866733, 0.52209879, 0.70989607, 0.28151634,
        0.12027041, 0.87103075],
       [0.08592456, 0.69971669, 0.14715851, 0.46886248, 0.56909596,
        0.07300845, 0.99423541],
       [0.33904997, 0.3891356 , 0.40041449, 0.71671602, 0.47692375,
        0.20627905, 0.93067501],
       [0.43718256, 0.30589863, 0.01960131, 0.42004158, 0.09490413,
        0.15040471, 0.23665186],
       [0.23068324, 0.1818081 , 0.43191804, 0.75529394, 0.16285912,
        0.0920792 , 0.05800474],
       [0.9342249 , 0.3558773 , 0.85649108, 0.30189895, 0.44277464,
        0.17087112, 0.46742222],
       [0.23229351, 0.30152906, 0.6176526 , 0.29188171, 0.07711749,
        0.61268868, 0.23488281],
       [0.03756255, 0.8753454 , 0.61219111, 0.40969578, 0.07642623,
        0.28279534, 0.31873742],
       [0.9089843 , 0.54706505, 0.45696665, 0.19321512, 0.46164848,
        0.08370198, 0.38240538],
       [0.26437046, 0.06435866, 0.871961  , 0.7439894 , 0.50310792,
        0.52225079, 0.3

## 9. Matrix addition

1.Automatically create 2 integer matrix which have values in the range of [-10, 30]

2.Print them to the screen

3.Perform matrix addition of the above 2 matrices and print the result to the screen.

In [18]:
g = np.random.randint(-10,30, (3,5))
g

array([[ 17,   4, -10,  29,  -5],
       [ -5,   2,  18,  27,  27],
       [ 22,  -1,  20,  11,   0]])

In [19]:
h = np.random.randint(-10,30, (3,5))
h

array([[16, -6,  9, 21, 24],
       [ 0, 22, 24, 12, -2],
       [18, 17,  0, 15,  2]])

In [20]:
g + h

array([[33, -2, -1, 50, 19],
       [-5, 24, 42, 39, 25],
       [40, 16, 20, 26,  2]])

In [21]:
# another way
np.add(g,h)

array([[33, -2, -1, 50, 19],
       [-5, 24, 42, 39, 25],
       [40, 16, 20, 26,  2]])

##########################################

In [22]:
g2 = np.random.randint(-10,30, (7,2))
g3 = np.random.randint(-10,30, (7,2))
print(g2)
print(g3)

[[ -1  23]
 [ 29   9]
 [ -2  11]
 [  9  19]
 [ -1  23]
 [-10  19]
 [ 26   4]]
[[17 18]
 [ 4  7]
 [ 5 28]
 [12  2]
 [ 7 19]
 [ 4 -9]
 [21 -6]]


In [23]:
g2 + g3

array([[16, 41],
       [33, 16],
       [ 3, 39],
       [21, 21],
       [ 6, 42],
       [-6, 10],
       [47, -2]])

In [24]:
# or 
np.add(g2,g3)

array([[16, 41],
       [33, 16],
       [ 3, 39],
       [21, 21],
       [ 6, 42],
       [-6, 10],
       [47, -2]])