##  1. Import Numpy

In [1]:
import numpy as np

## 2. Manually create a matrix 
Create a 3-by-5 matrix and print it out to the screen

In [2]:
a = np.array([(1,2,3,4,5), (6,7,8,9,10), (11,12,13,14,15)])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


## 3. Manually create a vector

Create a vector which has 10 elements and print it out to the screen

In [3]:
b = np.array([1,2,3,4,5,6,7,8,9,10])
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 4. Automatically create matrix

Automatically create a 3-by-5 matrix which has interger values in the range of [0, 100] 
Automatically create a 5-by-7 matrix which has interger values in the range of [0, 100]
Print out the above 2 matricces to the screen
Implementy matrix multiplication of the above 2 matrices and print the result to the screen (let us call this result matrixx is C)

In [4]:
n = np.random.randint(1,100,(3,5))
n

array([[79, 22, 11, 80, 38],
       [34, 90, 87, 53, 46],
       [ 9, 94, 35, 27, 21]])

In [5]:
m = np.random.randint(0,100,(5,7))
m

array([[34, 50, 44, 51, 96, 19, 92],
       [77, 18, 48, 83, 32, 26, 31],
       [96, 60, 49, 73, 90, 28, 97],
       [88, 34, 66, 88, 20, 61, 51],
       [63, 77, 97, 42, 96, 76, 97]])

In [6]:
c = n.dot(m)
c

array([[14870, 10652, 14037, 15294, 14526, 10149, 16783],
       [24000, 13884, 18039, 22151, 19450, 12151, 21522],
       [14603,  6777, 10442, 14074,  9578,  6838, 10551]])

## 5. Scalar multiplication

Input a number fromm keyboard and multiply this number with the above matrix C and print the result to the screen

In [7]:
x = int(input("Enter a Number = "))

Enter a Number = 10


In [8]:
x * c

array([[148700, 106520, 140370, 152940, 145260, 101490, 167830],
       [240000, 138840, 180390, 221510, 194500, 121510, 215220],
       [146030,  67770, 104420, 140740,  95780,  68380, 105510]])

## 6. Automatically create vector

Automattically create a vector at size of 7-by-1 which has values in the range of [-10, 30]. And multiply the C matrix with this vector. Print the result to the screen.

In [9]:
y = np.random.randint(-10,30,(7,1))
y

array([[10],
       [11],
       [-1],
       [ 4],
       [ 8],
       [-4],
       [ 8]])

In [10]:
cx_multiplication = c.dot(y)
print(cx_multiplication)

[[522887]
 [742461]
 [400111]]


##  7. Matrix slicing

1.Automatically create a matrix at size of 7-by-15

In [16]:
z = np.random.rand(7,15)
z

array([[0.75020041, 0.66367851, 0.48292804, 0.88690725, 0.53730965,
        0.07480383, 0.26320715, 0.83777855, 0.73512185, 0.95006086,
        0.46893986, 0.29206389, 0.47654658, 0.6271419 , 0.39270305],
       [0.20292721, 0.6170697 , 0.30662911, 0.64110241, 0.55771003,
        0.74091545, 0.55420348, 0.36550556, 0.06529895, 0.77466017,
        0.84993251, 0.11886275, 0.35693506, 0.81562146, 0.98181212],
       [0.83211784, 0.40604272, 0.4161388 , 0.20200112, 0.66054009,
        0.44241239, 0.99653059, 0.05627715, 0.86743703, 0.20480662,
        0.14775458, 0.20238938, 0.25030819, 0.03489005, 0.04042304],
       [0.62687175, 0.07182486, 0.26754344, 0.61541304, 0.47211997,
        0.40587019, 0.37004139, 0.57871981, 0.69172931, 0.3293049 ,
        0.28158537, 0.33203493, 0.320675  , 0.46251546, 0.21006383],
       [0.60240872, 0.07548048, 0.9116064 , 0.92927429, 0.18932856,
        0.31773255, 0.11458341, 0.48668625, 0.628719  , 0.60313136,
        0.68398894, 0.80471477, 0.22501805, 

2. Print out the first column of this matrix


In [29]:
z[0:7,0]

array([0.75020041, 0.20292721, 0.83211784, 0.62687175, 0.60240872,
       0.66005739, 0.47528844])

In [30]:
z[:,0]

array([0.75020041, 0.20292721, 0.83211784, 0.62687175, 0.60240872,
       0.66005739, 0.47528844])

3. Print out the third row of this matrix

In [31]:
z[2, :]

array([0.83211784, 0.40604272, 0.4161388 , 0.20200112, 0.66054009,
       0.44241239, 0.99653059, 0.05627715, 0.86743703, 0.20480662,
       0.14775458, 0.20238938, 0.25030819, 0.03489005, 0.04042304])

4.Print out the element at the second column and fourth row


In [39]:
z[3, 1]

0.07182486479825057

## 8. Matrix transposition

In [43]:
i = np.transpose(z)
i

array([[0.75020041, 0.20292721, 0.83211784, 0.62687175, 0.60240872,
        0.66005739, 0.47528844],
       [0.66367851, 0.6170697 , 0.40604272, 0.07182486, 0.07548048,
        0.50013478, 0.39856447],
       [0.48292804, 0.30662911, 0.4161388 , 0.26754344, 0.9116064 ,
        0.99281392, 0.25056758],
       [0.88690725, 0.64110241, 0.20200112, 0.61541304, 0.92927429,
        0.27200296, 0.69857182],
       [0.53730965, 0.55771003, 0.66054009, 0.47211997, 0.18932856,
        0.86939586, 0.81299919],
       [0.07480383, 0.74091545, 0.44241239, 0.40587019, 0.31773255,
        0.80793098, 0.06458558],
       [0.26320715, 0.55420348, 0.99653059, 0.37004139, 0.11458341,
        0.93836876, 0.38803669],
       [0.83777855, 0.36550556, 0.05627715, 0.57871981, 0.48668625,
        0.71782099, 0.32899115],
       [0.73512185, 0.06529895, 0.86743703, 0.69172931, 0.628719  ,
        0.86455256, 0.22475384],
       [0.95006086, 0.77466017, 0.20480662, 0.3293049 , 0.60313136,
        0.59217679, 0.1

## 9. Matrix addition

1.Automatically create 2 integer matrix which have values in the range of [-10, 30]

2.Print them to the screen

3.Perform matrix addition of the above 2 matrices and print the result to the screen.

In [51]:
g = np.random.randint(-10,30)
g

26

In [52]:
h = np.random.randint(-10,30)
h

5

In [53]:
g + h

31

In [58]:
# another way
np.add(g,h)

31

##########################################

In [60]:
g2 = np.random.randint(-10,30,2)
g3 = np.random.randint(-10,30,2)
print(g2)
print(g3)

[29 -6]
[21 26]


In [61]:
g2 + g3

array([50, 20])

In [63]:
# or 
np.add(g2,g3)

array([50, 20])